services:
  - type: web
    name: arquidesk
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
